# Site settings
title: Hong Nhung Pham
email: hongpham.analyst@gmail.com
description: Hong Nhung Pham's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hongnpham.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/