# Site settings
title: Hong N. Pham
logo: hong_2.jpg
email: hongpham.analyst@gmail.com
description: Master's student in Management in Data Analytics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hongnpham.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-minimal
show_downloads: yes
background-color : black

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/